### ISSUE TITLE
Add an example for node js

### ISSUE THREAD

**Issue by davi-miquelim** [josejoserojas/optimize-routes#1]
I am having trouble finding the docs for the Maps SDK, and it would be awesome to have NodeJs or React samples

**Comment by Loodico** [comment]
Hey davi-miquelim,

For the optimization route , here is the documentation page: https://developer.tomtom.com/routing-api/documentation/routing/calculate-route

And even the samples are in javascript, you can always add them in a Node.js application.
Check the routing section of the samples here: https://developer.tomtom.com/maps-sdk-web-js/functional-examples

I hope this can helps!

**Comment by davi-miquelim** [comment]
It did help, thanks for that
